# Project information
site_name: 'doccano'
site_description: 'A Text Annotation tool for Human'
site_author: 'Hiroki Nakayama'
site_url: 'https://chakki-works.github.io/doccano/'

# Repository
repo_name: 'chakki-works/doccano'
repo_url: 'https://github.com/quinnpertuit/prolabel'

# Copyright
copyright: 'AIHR'

theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  show_sidebar: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/quinnpertuit1'

# Page tree
nav:
  - Doccano: index.md
  - Getting started: getting-started.md
  - Tutorial: tutorial.md
  - Advanced:
    - AWS HTTPS settings: advanced/aws_https_settings.md
    - OAuth2 settings: advanced/oauth2_settings.md
  #- Release notes: release-notes.md
  #- Author's notes: authors-notes.md
  - FAQ: faq.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Roadmap: roadmap.md
  - License: LICENSE.md
