# Project information
site_name: 'pro-label'
site_description: 'AIHR Text Annotation tool'
site_author: 'Quinn Pertuit'
site_url: 'https://github.com/quinnpertuit1/prolabel'

# Repository
repo_name: 'quinnpertuit1/prolabel'
repo_url: 'https://github.com/quinnpertuit1/prolabel'

# Copyright
copyright: 'AIHR'

theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  show_sidebar: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/quinnpertuit1'

# Page tree
nav:
  - Pro-Label: index.md
  - Getting started: getting-started.md
  - Tutorial: tutorial.md
  - Advanced:
    - AWS HTTPS settings: advanced/aws_https_settings.md
    - OAuth2 settings: advanced/oauth2_settings.md
